name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Set your Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --prod

    - name: Deploy to Google Cloud Storage
      uses: google-github-actions/deploy-cloud-storage@v0.6.0
      with:
        path: dist/d2l-clone  # Replace with the path to your build directory
        bucket: ${{ secrets.GCS_BUCKET }}
        credentials: ${{ secrets.GCS_SA_KEY }}