name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # Set your branch name here

jobs:
  deploy:
    runs-on: ubuntu-latest

        # Add "id-token" with the intended permissions.
    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Set your Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/76621810654/locations/global/workloadIdentityPools/d2l-pool/providers/github-provider'
        service_account: 'd2l-181@arctic-cyclist-398917.iam.gserviceaccount.com'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist/d2l-clone'
        destination: 'd2l-fe'